eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8060/eureka
server:
  port: 8600
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
#      url: http://localhost:8061/
      serviceId: client-1