server:
  port: 8060
eureka:
  instance:
    hostname: localhost
  client:
    #    在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
    #    eureka.client. register-with-eureka:由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    registerWithEureka: false
    #    eureka. client . fetch-registry:由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false。 不主动发现别人
    fetchRegistry: false
    #    声明注册中心的地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#给当前应用起个服务名称
spring:
  application:
    name: eureka-server
