server:
  port: 8075
spring:
  application:
    name: client-5
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8060/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"

